baseurl = "https://themachinelearnedit.online"
languageCode = "en-us"
title = "The Machine Learned It Online"
theme = "hugo-lithium"
googleAnalytics = "UA-172912816-1"
disqusShortname = "@matthewrowse"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
enableRobotsTXT = true
canonifyURLs = true

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/"
[[menu.main]]
    name = "LinkedIn"
    url = "https://twitter.com/rstudio"

[params]
    description = "A blog about learning R for business analysis and machine learning"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

