---
author: Matt
title: My Test Dashboard
output:
  flexdashboard::flex_dashboard:
    theme: cosmo
    social: null
    source: null
    navbar: []
runtime: shiny
---

```{r i2dash-global-setup}
# Deal with operation within a switchr environment
if (any(grepl(pattern = ".switchr", x = .libPaths()))) {
  switchr::switchrNoUnload(TRUE)
}

# Make it possible to reuse chunk labels
options(knitr.duplicate.label = "allow")

# Set datadir variable, components should fetch their env from here!
datadir <- "C:/Users/mattr/OneDrive/Documents/R/themachinelearnedit.online"

# Set up color mappings
colormaps <- list()
```

Home Page {data-navmenu=""}
====================================================

<!-- Page created on 2020-07-29 19:04:41 -->


Column {data-width=600}
-------------------------------------
    
### Plotly example

<!-- Component created on 2020-07-29 19:04:40 -->

```{r}
if (!requireNamespace("plotly", quietly = TRUE)) {
    stop('The package "plotly" is needed to embed objects of class "plotly".', call. = FALSE)
}

vis_obj_cDr3pL <- readRDS(file.path(datadir, 'obj_cDr3pL.rds'))

# workaround for plotly dependencies issue (https://github.com/ropensci/plotly/issues/1044)
# 
fix_dependency <- function(dependency){
  if(dependency$name == "crosstalk" & dependency$version == "1.1.0"){
    if(dependency$name == "jquery") dependency$src$file <- file.path(system.file(package ="crosstalk"), "lib/jquery")
    if(dependency$name == "crosstalk") dependency$src$file <- file.path(system.file(package ="crosstalk"), "www")
  }
  return(dependency)
}
if ("plotly" == "plotly"){
  vis_obj_cDr3pL$dependencies <- lapply(vis_obj_cDr3pL$dependencies, fix_dependency)  
}

vis_obj_cDr3pL
```


   
Column {data-width=400}
-------------------------------------
   




Cars Data {data-navmenu="My Menu Link"}
====================================================

<!-- Page created on 2020-07-29 19:04:41 -->


Column {data-width=600}
-------------------------------------
    
### Sweet plot

<!-- Component created on 2020-07-29 19:04:39 -->

```{r}
if (!requireNamespace("ggplot2", quietly = TRUE)) {
    stop('The package "ggplot2" is needed to embed objects of class "gg".', call. = FALSE)
}

vis_obj_ECBQJh <- readRDS(file.path(datadir, 'obj_ECBQJh.rds'))

# workaround for plotly dependencies issue (https://github.com/ropensci/plotly/issues/1044)
# 
fix_dependency <- function(dependency){
  if(dependency$name == "crosstalk" & dependency$version == "1.1.0"){
    if(dependency$name == "jquery") dependency$src$file <- file.path(system.file(package ="crosstalk"), "lib/jquery")
    if(dependency$name == "crosstalk") dependency$src$file <- file.path(system.file(package ="crosstalk"), "www")
  }
  return(dependency)
}
if ("ggplot2" == "plotly"){
  vis_obj_ECBQJh$dependencies <- lapply(vis_obj_ECBQJh$dependencies, fix_dependency)  
}

vis_obj_ECBQJh
```


   
Column {data-width=400}
-------------------------------------
   




Narangba {data-navmenu="My Menu Link"}
====================================================

<!-- Page created on 2020-07-29 19:04:41 -->


Column {data-width=600}
-------------------------------------
    
### Sweet map

<!-- Component created on 2020-07-29 19:04:39 -->

```{r}
if (!requireNamespace("leaflet", quietly = TRUE)) {
    stop('The package "leaflet" is needed to embed objects of class "leaflet".', call. = FALSE)
}

vis_obj_4q5x7r <- readRDS(file.path(datadir, 'obj_4q5x7r.rds'))

# workaround for plotly dependencies issue (https://github.com/ropensci/plotly/issues/1044)
# 
fix_dependency <- function(dependency){
  if(dependency$name == "crosstalk" & dependency$version == "1.1.0"){
    if(dependency$name == "jquery") dependency$src$file <- file.path(system.file(package ="crosstalk"), "lib/jquery")
    if(dependency$name == "crosstalk") dependency$src$file <- file.path(system.file(package ="crosstalk"), "www")
  }
  return(dependency)
}
if ("leaflet" == "plotly"){
  vis_obj_4q5x7r$dependencies <- lapply(vis_obj_4q5x7r$dependencies, fix_dependency)  
}

vis_obj_4q5x7r
```


   
Column {data-width=400}
-------------------------------------
   




