---
title: Where do I start to learn R?
author: Matt Rowse
date: '2020-07-17'
slug: where-do-i-start-to-learn-r
categories: []
tags:
  - R
  - edX
  - John Hopkins
  - Datacamp
  - Youtube
  - Business Science
---
Because at heart I am the frugal tight arsed type, when looking for what options were available to start my journey, I did some research that might save you some time. 

If you like to learn interactively, [Datacamp](datacamp.com.au) is hard to go past, particularly if you take advantage of some of the free trial offers you might get signing up for active deals like [this one](https://visualstudio.microsoft.com/dev-essentials/) that at the time of writing this gives you 2 months free access if you sign up with your details, plus some other goodies.

This free Chromebook user focused course is provided at a 'whatever you want to pay' price, from [John Hopkins Bloomberg School of Public health](http://jhudatascience.org/chromebookdatascience/cbds.html). As it's aim is to teach you to use powerful machines online, rather than having to have a powerful PC at your fingertips, it is a good resource for learning how to structure cloud based data science project management.

Once I had done both of the above courses, I started to look for something to make it 'official' and looked around for data science certification options. This search took me to [edX Online](edx.org) which I have found to be a fantastic resource. The data science certificate is very challenging and takes your programming capability to the next level, while for me padded out my understanding of the science behind the algorithms. edX offers a large range of courses for no charge, unless you want the certification which you will need to fork out for and complete some verified assesments. These courses have excellent video content, along with the code you can utilise elsewhere once you know how to read it. The certification would have cost me around $400AUD all up, which I saw to be pretty good value all things considered and looks great on my resume.

Beyond this as I am primarily a business user more than a data scientist, I looked for a business focussed R training provider and came across [Business Science](https://www.business-science.io/) which again has some excellent content, particularly as you start to move away from just creating a script, to create one-off visualisations and reports, to putting R into production environments, where you can publish interactive dashboards and reach more users with your projects on a larger scale.

If you haven't looked yet, check out [Youtube](youtube.com) as well, as there is a heap of excellent free content out there, some that includes the code to follow. [This guy](https://www.youtube.com/user/westlandindia) in particular is worth subscribing to as I found the content to be bite sized, easy to follow and code included - he is one very smart dude.

Other than that I follow [Rbloggers](https://www.r-bloggers.com/) regularly, which has a large community of users sharing their favourite packages you could add to your repetoire and helps to stay up to date with new packages coming out. There are usually a few posts each day and the variety keeps it interesting.

And of course if you have a specific question as you're learning, you aren't the first person to have that problem, so googling the error will likely return the answer after some research or good reads like [this one](https://r4ds.had.co.nz/).

If you can afford it I would recommend to start with the Business Science courses, as I found they were very targeted on specific sets of flexible packages, meaning you can get up to speed very quickly. They work on the 80/20 rule and it's very effective as there are some core packages to learn like the Tidyverse and Tidymodels, which bring repeated structural benefits.